global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'express-server'
    static_configs:
      - targets: ['expressjs:3000']  # Using your Docker service name
    metrics_path: '/metrics'  # Default Prometheus client endpoint

rule_files:
  - 'alert.rules.yml'